# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269123b1e39ed0f1a943b8b489e9d5d23ad5ae6ea0f53f6880a705748dd2fe48259f0a8728377af4242753475121e71778755971cf9e07f57bd59d047778542d

test:
  secret_key_base: 73cdb4c4fc3d07f1b1d958b44d4a790faf8864490cd977267c800c65fef61851fb22f67c96eb15ff82c1dab4db67297a5398bdcf450c796911e8c1b2200522b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
